import {
  Heart,
  Home,
  Users,
  Briefcase,
  Clock,
  FileText,
  FileCheck,
  ShieldCheck,
  IdCard,
  Landmark,
  Gavel,
  MessageCircle,
  Plane,
  Calendar,
  AlertTriangle,
  Scale,
  Globe,
  ClipboardCheck,
  UserCheck,
  Building2,
  GraduationCap,
  HelpCircle,
  Award,
  FileSearch,
  Upload,
  Stamp,
  Headset,
  Palmtree,
  Compass,
  Mountain,
} from "lucide-react";

// String-keyed icon registry so service configuration data can reference
// icons by name instead of importing lucide components directly.
export const ICONS = {
  heart: Heart,
  home: Home,
  users: Users,
  briefcase: Briefcase,
  clock: Clock,
  "file-text": FileText,
  "file-check": FileCheck,
  "shield-check": ShieldCheck,
  "id-card": IdCard,
  landmark: Landmark,
  gavel: Gavel,
  "message-circle": MessageCircle,
  plane: Plane,
  calendar: Calendar,
  "alert-triangle": AlertTriangle,
  scale: Scale,
  globe: Globe,
  "clipboard-check": ClipboardCheck,
  "user-check": UserCheck,
  building: Building2,
  "graduation-cap": GraduationCap,
  "help-circle": HelpCircle,
  award: Award,
  "file-search": FileSearch,
  upload: Upload,
  stamp: Stamp,
  headset: Headset,
  "palm-tree": Palmtree,
  compass: Compass,
  mountain: Mountain,
};

export function getIcon(key) {
  return ICONS[key] || HelpCircle;
}
